### ISSUE TITLE
Add reset button

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_ui#105]
There should be a way to reset the app, deleting the in-browser database.

**Comment by yeliztaneroglu** [comment]
Hi @gordonbrander, I want to fix this issue, so I'm researching now :) Please Could you give me more information ? Thank you.

**Comment by gordonbrander** [comment]
Oops! This was already done! https://github.com/OpenAgInitiative/openag_ui/pull/122

**Comment by gordonbrander** [comment]
@yeliztaneroglu It would be great to get your help on other items though! This might be a good one https://github.com/OpenAgInitiative/openag_ui/issues/118.

**Comment by yeliztaneroglu** [comment]
Great!! Okey I'm investigating :) thanks @gordonbrander.

**Comment by gordonbrander** [comment]
@yeliztaneroglu great! LMK if I can help.
