### ISSUE TITLE
RFC: Host UI as CouchApp

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_ui#126]
## Goal

Host the Food Computer UI from the FC's IP address.

## Plan

I'm planning to create a build option to host the UI as a CouchApp from CouchDB.

Couch has the ability to serve up static files using its built-in server. This is essentially how Futon, the CouchDB UI works. They used to encourage 3rd party app developers to create apps this way, but it seems to have gone out of style. However, there are some up-to-date tools for this that they use for Futon, like this NPM package https://www.npmjs.com/package/couchapp.

@LeonChambers do you have any objections or opinions about this approach?

**Comment by LeonChambers** [comment]
I think this makes a lot of sense. Since the app is just a bunch of static files, it should be pretty simple to have Couch serve them.
