### ISSUE TITLE
install instructions should mention need to enable CORS in couchdb

### ISSUE THREAD

**Issue by yaromins** [OpenAgInitiative/openag_ui#22]
I was trying to play with this code, but have found that adding recipe does not work due to CORS being disabled by default in CouchDb.
Enabling CORS helped to avoid cross origin errors in console, but I've stuck further on with some other error:

> node.js:152 Uncaught TypeError: Cannot read property '$type' of undefined

**Comment by gordonbrander** [comment]
You're right! This repo is meant to act as a UI layer on top of https://github.com/openaginitiative/openag-brain, which itself is a work in progress. openag-brain is the backend component that runs CouchDB. Will update README.

**Comment by gordonbrander** [comment]
Filed in openag-brain https://github.com/OpenAgInitiative/openag_brain/issues/9
