### ISSUE TITLE
Install and build on RPi 2

### ISSUE THREAD

**Issue by MisterBurnley** [OpenAgInitiative/openag_ui#82]
Further to input on forum, have restarted the Pi and executed npm install. It appears to work with no errors. Executing npm run build gives the following:

> openag-ui@0.0.1 build /home/pi/openag_ui-master
> grunt build

Loading "browserify.js" tasks...ERROR

> > Error: Cannot find module 'module-deps'
> > Loading "watch.js" tasks...ERROR
> > SyntaxError: /home/pi/openag_ui-master/node_modules/grunt-contrib-watch/node_modules/gaze/node_modules/globule/node_modules/lodash/lodash.js:13893
> >     /**
> >     ^^^
> > Unexpected token ILLEGAL
> > Warning: Task "browserify:dist" not found. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! openag-ui@0.0.1 build: `grunt build`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the openag-ui@0.0.1 build script 'grunt build'.
npm ERR! This is most likely a problem with the openag-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system: than I got the first time
npm ERR!     grunt build
npm ERR! You can get their info via:
npm ERR!     npm owner ls openag-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/openag_ui-master/npm-debug.log

from what I remember these are different errors from those I got the first time. I intend to delete the folder and unzip the ui download and try again to see if there is any difference to the errors.

**Comment by gordonbrander** [comment]
@MisterBurnley I just ran a build and had no problem. Maybe your repository is out of date? However the build just generates a flat HTML file that can be hosted online or on the Pi. You shouldn't have to build the UI yourself unless you're developing it.

If you just want to use the UI, visit http://openaginitiative.github.io/openag_ui/.
