### ISSUE TITLE
npm run build is failing

### ISSUE THREAD

**Issue by yaromins** [OpenAgInitiative/openag_ui#95]
@gordonbrander, just pulled latest changes from master and can't build dist with `npm run build`:

> grunt build
> Running "browserify:dist" (browserify) task
> >> Error: Cannot find module './dashboard/sidebar' from '/home/serein/Projects/openAgInitiative/openag_ui/scripts/environment'
> Warning: Error running grunt-browserify. Use --force to continue.
> Aborted due to warnings.
> npm ERR! Linux 4.4.0-36-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
> npm ERR! node v6.5.0
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! openag-ui@0.0.1 build: `grunt build`
> npm ERR! Exit status 6

**Comment by gordonbrander** [comment]
Yeah, that was my darn fault. Fixed https://github.com/OpenAgInitiative/openag_ui/pull/96.
